#!/bin/bash

set -o xtrace

dist=`stack path --dist-dir --stack-yaml ./stack.yaml 2> /dev/null`

echo -e "\033[1;36mTesting library...\033[0m"
stack test 2> /dev/null

echo -e "\033[1;36mRunning sdist...\033[0m"
cabal sdist

echo -e "\033[1;36mGenerating documentation...\033[0m"
stack haddock 2> /dev/null

if [ "$?" -eq "0" ]; then
  echo -e "\033[1;32mUploading package to Hackage...\033[0m"
  read -p "Hackage username: " username
  read -p "Hackage password: " -s password
  echo ""
  cabal upload -u $username -p $password dist/$1-$2.tar.gz

  docdir=$dist/doc/html
  cd $docdir
  doc=$1-$2-docs

  echo -e "Compressing documentation from \033[1;34m$docdir\033[0m for \033[1;35m$1\033[0m-\033[1;33m$2\033[1;30m"
  cp -r $1 $doc
  tar -c -v -z --format=ustar -f $doc.tar.gz $doc
  echo -e "\033[1;32mUploading documentation to Hackage...\033[0m"
  curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@$doc.tar.gz" "https://$username:$password@hackage.haskell.org/package/$1-$2/docs"
  exit $?
else
  echo -e "\033[1;31mNot in a stack-powered project\033[0m"
fi
